add conduit changes

diff --git a/sandbox b/sandbox
--- a/sandbox
+++ b/sandbox
@@ -15,6 +15,7 @@ FAST_CATCHUP_URL='https://algorand-catchpoints.s3.us-east-2.amazonaws.com/channe
 APORT="${ALGOD_PORT:-4001}"
 KPORT="${KMD_PORT:-4002}"
 IPORT="${INDEXER_PORT:-8980}"
+CPORT="${CONDUIT_PORT:-3998}"
 
 # Global flags
 USE_FAST_CATCHUP=1
@@ -36,6 +37,10 @@ export INDEXER_URL=""
 export INDEXER_BRANCH=""
 export INDEXER_SHA=""
 export INDEXER_DISABLED=""
+export CONDUIT_URL=""
+export CONDUIT_BRANCH=""
+export CONDUIT_SHA=""
+export CONDUIT_DISABLED=""
 
 ##################################################
 # Determine the correct docker command (or fail) #
@@ -196,11 +201,13 @@ sandbox () {
     goal_helper node status
     statusline "algorand-indexer - health"
     curl -s "localhost:$IPORT/health?pretty"
+    statusline "conduit - imported metric"
+    curl -s "localhost:$CPORT/metrics"|grep -e "^conduit_imported_round" -e "^Conduit disabled"
   }
 
   # docker-compose alias
   # must only be used when no pseudo-TTY is required
-  # in particular, when using 
+  # in particular, when using
   #   dc ... exec ...
   # the flag -T needs to be passed
   # Concretely, to execute non-interactive commands:
@@ -261,11 +268,10 @@ sandbox () {
       then
           echo "tealdbg debug command called without --listen option therefore sandbox attached the option automatically!"
           dc exec -T algorand-algod tealdbg  "$@" --listen 0.0.0.0
-          
       else
           dc exec -T algorand-algod tealdbg "$@"
-      fi        
-    fi    
+      fi
+    fi
   }
 
   # wait until algorand-indexer/algorand-algod health endpoints report 200
@@ -283,6 +289,12 @@ sandbox () {
           INDEXER_STATUS="200"
       fi
 
+      if [ -z "$CONDUIT_DISABLED" ]; then
+          CONDUIT_STATUS=$(curl -sL -w "%{http_code}\n" "localhost:$CPORT/metrics" -o /dev/null || true)
+      else
+          CONDUIT_STATUS="200"
+      fi
+
       ALGOD_STATUS=$(curl -sL -w "%{http_code}\n" "localhost:$APORT/health" -o /dev/null || true)
       if [ "$ALGOD_STATUS" == "200" ] && [ "$INDEXER_STATUS" == "200" ]; then
         ATTEMPTS_REMAINING=0
@@ -298,7 +310,10 @@ sandbox () {
         echo "* algorand node"
       fi
       if [ "$INDEXER_STATUS" != "200" ]; then
-        echo "* algorand-indexer node"
+        echo "* indexer"
+      fi
+      if [ "$CONDUIT_STATUS" != "200" ]; then
+        echo "* conduit"
       fi
       err "One or more services failed to start."
     fi
@@ -353,8 +368,58 @@ sandbox () {
       fi
     done
 
-    overwrite "* Account processing complete."
+    overwrite "* Account download complete."
+    # Newline for the progress bar to use.
+    echo ""
 
+    DONE=false
+    STARTED=false
+    while [ $DONE == "false" ]; do
+      sleep 0.1
+
+      local RES
+      local TOTAL
+      local PROGRESS
+
+      RES="$(status_helper)"
+      STARTED=true
+      TOTAL=$(echo $RES | grep -o 'Catchpoint total KVs: [[:digit:]]*' | cut -d':' -f 2 )
+      PROGRESS=$(echo $RES | grep -o 'Catchpoint KVs processed: [[:digit:]]*' | cut -d':' -f 2 )
+
+      if [ $TOTAL == $PROGRESS ]; then
+        DONE=true
+      else
+        progress_bar "Processing boxes:" "$PROGRESS" "$TOTAL"
+      fi
+    done
+
+    overwrite "* Box processing complete."
+
+    # Newline for the progress bar to use.
+    echo ""
+
+    DONE=false
+    STARTED=false
+    while [ $DONE == "false" ]; do
+      sleep 0.1
+
+      local RES
+      local TOTAL
+      local PROGRESS
+
+      RES="$(status_helper)"
+      STARTED=true
+      TOTAL=$(echo $RES | grep -o 'Catchpoint total accounts: [[:digit:]]*' | cut -d':' -f 2 )
+      PROGRESS=$(echo $RES | grep -o 'Catchpoint accounts verified: [[:digit:]]*' | cut -d':' -f 2 )
+
+      if [ $TOTAL == $PROGRESS ]; then
+        DONE=true
+      else
+        progress_bar "Verifying accounts:" "$PROGRESS" "$TOTAL"
+      fi
+    done
+
+    overwrite "* Account validation complete."
     # Newline for the progress bar to use.
     echo ""
 
@@ -411,17 +476,12 @@ sandbox () {
   enter () {
     CONTAINER=${2:-}
     if [ -z "$CONTAINER" ]; then
-        err "'enter' requires a container. Available containers: algorand-algod, algorand-indexer, algorand-indexer-db, asc-alice, asc-bob"
+        err "'enter' requires a container. Available containers: algorand-algod, algorand-conduit, algorand-indexer, algorand-indexer-db, asc-alice, asc-bob"
     fi
     case $CONTAINER in
-      algorand-algod)
-        statusline "Entering /bin/bash session in the algorand-algod container..."
-        dc_pty exec algorand-algod //bin/bash
-        return
-        ;;
-      algorand-indexer)
-        statusline "Entering /bin/bash session in the algorand-indexer container..."
-        dc_pty exec algorand-indexer //bin/bash
+      algorand-algod|algorand-indexer|algorand-conduit)
+          statusline "Entering /bin/bash session in the $CONTAINER container..."
+          dc_pty exec $CONTAINER //bin/bash
         return
         ;;
       algorand-indexer-db)
@@ -458,12 +518,24 @@ sandbox () {
   # One-time dump of logs of a particular service to the shell
   dump() {
     case $2 in
-      algorand-algod|algorand-indexer|algorand-indexer-db)
+      algorand-algod|algorand-indexer|algorand-conduit|algorand-indexer-db)
         dc logs "$2"
         ;;
 
       *)
-        err "Cannot dump '$2'. Available containers: algorand-algod, algorand-indexer, algorand-indexer-db"
+        err "Cannot dump '$2'. Available containers: algorand-algod, algorand-conduit, algorand-indexer, algorand-indexer-db"
+        ;;
+    esac
+  }
+
+  tail_f() {
+    case $2 in
+      algorand-algod|algorand-indexer|algorand-conduit|algorand-indexer-db)
+        dc logs --follow "$2"
+        ;;
+
+      *)
+        err "Cannot tail '$2'. Available containers: algorand-algod, algorand-conduit, algorand-indexer, algorand-indexer-db"
         ;;
     esac
   }
@@ -545,8 +617,10 @@ sandbox () {
       wait_for_services
       echo "* services ready!"
 
+      set +e
       version_helper
       status_helper
+      set -e
 
       if [ -z $NETWORK_GENESIS_FILE ]; then
         #####################
@@ -597,10 +671,12 @@ sandbox commands:
   reset           -> reset the containers to their initial state.
   clean           -> stops and deletes containers and data directory.
   test            -> runs some tests to demonstrate usage.
-  enter [algorand-algod||algorand-indexer||algorand-indexer-db||asc-alice||asc-bob]
+  enter [algorand-algod||algorand-conduit||algorand-indexer||algorand-indexer-db||asc-alice||asc-bob]
                   -> enter the sandbox container.
-  dump [algorand-algod||algorand-indexer||algorand-indexer-db]
+  dump [algorand-algod||algorand-conduit||algorand-indexer||algorand-indexer-db]
                   -> dump log information for a container.
+  tail [algorand-algod||algorand-conduit||algorand-indexer||algorand-indexer-db]
+                  -> tail log information for a container.
   version         -> print binary versions.
   copyTo <file>   -> copy <file> into the algorand-algod. Useful for offline transactions, offline LogicSigs & TEAL work.
   copyFrom <file> -> copy <file> from the algorand-algod. Useful for offline transactions, offline LogicSigs & TEAL work.
@@ -685,11 +761,11 @@ EOF
 
       TOKEN=$(cat "$SANDBOX_DIR/config/token")
       statusline "Test algorand-algod REST API..."
-      printc $default "~$ ${blue}curl ${teal}localhost:$APORT/v2/status?pretty -H \"X-Algo-API-Token: $TOKEN\""
+      printc $default "~$ ${blue}curl ${teal}\"localhost:$APORT/v2/status?pretty\" -H \"X-Algo-API-Token: $TOKEN\""
       curl "localhost:$APORT/v2/status?pretty" -H "X-Algo-API-Token: $TOKEN"
 
       statusline "Test KMD REST API..."
-      printc $default "~$ ${blue}curl ${teal}localhost:$KPORT/v1/wallets -H \"X-KMD-API-Token: $TOKEN\""
+      printc $default "~$ ${blue}curl ${teal}\"localhost:$KPORT/v1/wallets\" -H \"X-KMD-API-Token: $TOKEN\""
       curl "localhost:$KPORT/v1/wallets" -H "X-KMD-API-Token: $TOKEN"
 
       statusline "\nTest algorand-indexer REST API..."
@@ -707,6 +783,10 @@ EOF
 
     dump)
       dump "$@"
+      ;;
+
+    tail)
+      tail_f "$@"
       ;;
 
     status)
@@ -735,7 +815,7 @@ EOF
 
     copyFrom|cpf)
       shift
-      statusline "Now copying  /opt/data/$1 from algorand-algod container to $SANDBOX_DIR/" 
+      statusline "Now copying  /opt/data/$1 from algorand-algod container to $SANDBOX_DIR/"
       docker cp "$(dc ps -q algorand-algod):/opt/data/$(basename $1)" "$1"
       ;;
 
